export const UNAUTHORIZED_ERROR = '아이디 및 비밀번호를 확인해주세요.'
export const LABEL_EMAIL = 'Email'
export const LABEL_PASSWORD = 'Password'
export const REQUIRED_EMAIL = '이메일을 입력해주세요.'
export const REQUIRED_PASSWORD = '비밀번호를 입력해주세요.'
